apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: inspect-query-service
  description: Spring Boot microservice for inspection queries
  annotations:
    github.com/project-slug: pharikrishna/inspect-query-service
    backstage.io/techdocs-ref: dir:.
    backstage.io/scaffolder-template: promote-to-qa
spec:
  type: service
  lifecycle: production
  owner: platform-team
