# catalog-info.yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    github.com/project-slug: pharikrishna/inspect-query-service
spec:
  type: service
  lifecycle: production
  owner: Amogh
